import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { MatPaginator } from '@angular/material/paginator';
import { MatTable, MatTableDataSource } from '@angular/material/table';
import { Contact } from 'src/app/models/contact.model';

@Component({
  selector: 'app-contact-list',
  templateUrl: './contact-list.component.html',
  styleUrls: ['./contact-list.component.css'],
})
export class ContactListComponent implements AfterViewInit {
  displayedColumns: string[] = [
    'id',
    'firstName',
    'lastName',
    'email',
    'dob',
    'gender',
    'education',
    'company',
    'experience',
    'package',
  ];
  dataSource = new MatTableDataSource<Contact>(ELEMENT_DATA);
  pageSizeOptions = [5, 10, 20];
  @ViewChild(MatPaginator) paginator!: MatPaginator;
  @ViewChild(MatTable) contactTable!: MatTable<Contact>;

  ngAfterViewInit() {
    this.dataSource.paginator = this.paginator;
    this.contactTable.renderRows();
  }
}

const ELEMENT_DATA: Contact[] = [
  {
    id: 1,
    firstName: 'Alice',
    lastName: 'Johnson',
    email: 'alice.johnson@example.com',
    dob: '1992-03-12',
    gender: 'Female',
    education: 'Bachelor',
    company: 'Tech Innovators',
    experience: 4,
    package: 75000,
  },
  {
    id: 2,
    firstName: 'Bob',
    lastName: 'Smith',
    email: 'bob.smith@example.com',
    dob: '1985-07-28',
    gender: 'Male',
    education: 'High School',
    company: 'Data Wizards',
    experience: 10,
    package: 120000,
  },
  {
    id: 3,
    firstName: 'Eva',
    lastName: 'Martinez',
    email: 'eva.martinez@example.com',
    dob: '1990-11-05',
    gender: 'Female',
    education: 'Master',
    company: 'Innovate Solutions',
    experience: 6,
    package: 90000,
  },
  {
    id: 4,
    firstName: 'Charlie',
    lastName: 'Brown',
    email: 'charlie.brown@example.com',
    dob: '1988-09-18',
    gender: 'Male',
    education: 'Bachelor',
    company: 'Code Crafters',
    experience: 8,
    package: 110000,
  },
  {
    id: 5,
    firstName: 'Diana',
    lastName: 'Miller',
    email: 'diana.miller@example.com',
    dob: '1995-02-22',
    gender: 'Female',
    education: 'High School',
    company: 'Future Tech',
    experience: 3,
    package: 65000,
  },
  {
    id: 6,
    firstName: 'Frank',
    lastName: 'Taylor',
    email: 'frank.taylor@example.com',
    dob: '1987-06-14',
    gender: 'Male',
    education: 'Master',
    company: 'InnoTech Solutions',
    experience: 7,
    package: 95000,
  },
  {
    id: 7,
    firstName: 'Grace',
    lastName: 'Wong',
    email: 'grace.wong@example.com',
    dob: '1993-12-09',
    gender: 'Female',
    education: 'Bachelor',
    company: 'Digital Creators',
    experience: 5,
    package: 80000,
  },
  {
    id: 8,
    firstName: 'Henry',
    lastName: 'Chen',
    email: 'henry.chen@example.com',
    dob: '1986-04-30',
    gender: 'Male',
    education: 'High School',
    company: 'InnoData Solutions',
    experience: 9,
    package: 100000,
  },
  {
    id: 9,
    firstName: 'Isabel',
    lastName: 'Lopez',
    email: 'isabel.lopez@example.com',
    dob: '1991-08-17',
    gender: 'Female',
    education: 'Master',
    company: 'Smart Systems',
    experience: 6,
    package: 92000,
  },
  {
    id: 10,
    firstName: 'Jack',
    lastName: 'Williams',
    email: 'jack.williams@example.com',
    dob: '1989-01-25',
    gender: 'Male',
    education: 'Bachelor',
    company: 'Tech Visionaries',
    experience: 8,
    package: 108000,
  },
  {
    id: 11,
    firstName: 'Karen',
    lastName: 'Turner',
    email: 'karen.turner@example.com',
    dob: '1994-06-07',
    gender: 'Female',
    education: 'High School',
    company: 'CodeGenius',
    experience: 4,
    package: 72000,
  },
  {
    id: 12,
    firstName: 'Leo',
    lastName: 'Nguyen',
    email: 'leo.nguyen@example.com',
    dob: '1984-10-14',
    gender: 'Male',
    education: 'Master',
    company: 'DataCraft',
    experience: 11,
    package: 125000,
  },
  {
    id: 13,
    firstName: 'Mia',
    lastName: 'Garcia',
    email: 'mia.garcia@example.com',
    dob: '1992-04-03',
    gender: 'Female',
    education: 'Bachelor',
    company: 'InnoSolutions',
    experience: 7,
    package: 96000,
  },
  {
    id: 14,
    firstName: 'Oscar',
    lastName: 'Brown',
    email: 'oscar.brown@example.com',
    dob: '1986-12-19',
    gender: 'Male',
    education: 'High School',
    company: 'Digital Innovators',
    experience: 10,
    package: 112000,
  },
  {
    id: 15,
    firstName: 'Pamela',
    lastName: 'Lewis',
    email: 'pamela.lewis@example.com',
    dob: '1990-02-08',
    gender: 'Female',
    education: 'Master',
    company: 'Tech Solutions',
    experience: 6,
    package: 92000,
  },
];
